name: pytorch-mnist

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - pip=20.1
  - pytorch=1.6.0
  - torchvision=0.7.0
  - cpuonly
  - pip:
      - analytics-zoo[torch]