name: pytorch-mnist

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - cpuonly
  - pip=20.1
  - pytorch=1.6.0
  - torchvision=0.7.0
  - cpuonly
  - pip:
      - analytics-zoo==0.9.0.dev0
      - jep==3.9.0
      - cloudpickle==1.2.2